# Maven
# Build your Java project and run tests with Apache Maven.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/java

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

steps:
#- task: Maven@3
#  inputs:
#    mavenPomFile: 'pom.xml'
#    mavenOptions: '-Xmx3072m'
#    javaHomeOption: 'JDKVersion'
#    jdkVersionOption: '1.8'
#    jdkArchitectureOption: 'x64'
#    publishJUnitResults: true
#    testResultsFiles: '**/surefire-reports/TEST-*.xml'
#    goals: 'package'

#Run tests using appsurify shell command
- bash: chmod +x RunTestsWithAppsurify.sh GetAndRunTests.sh PushResultsToAppsurify.sh GetResultsFromAppsurify.sh
  displayName: "Set permissions"  
#- bash: ./RunTestsWithAppsurify.sh --url "https://demo.appsurify.com" --apikey "MTU6a3Q1LUlTU3ZEcktFSTFhQUNoYy1DU3pidkdz" --project "Healthcare Value Stream" --testsuite "Selenium" --report "./results/" --reporttype "directory" --teststorun "high" --startrun "mvn -Dtest=" --fullname "true" --fullnameseparator "#" --endrun " test" --testseparator ","
#  displayName: "Run tests with Appsurify"
- bash: ./RunTestsWithAppsurify.sh --url "https://appsurify.dev.appsurify.com" --apikey "MTpEbzhXQThOaW14bHVQTVdZZXNBTTVLT0xhZ00" --project "Healthcare Value Stream" --testsuite "Selenium" --report "./results/" --reporttype "directory" --teststorun "high" --startrun "mvn -Dtest=" --fullname "true" --fullnameseparator "#" --endrun " test" --testseparator ","
  displayName: "Run tests with Appsurify"



# Use Python version
# Use the specified version of Python from the tool cache, optionally adding it to the PATH
#- task: UsePythonVersion@0
#  inputs:
#    versionSpec: '3.7' 
#    addToPath: true 
#    #architecture: 'x64' # Options: x86, x64 (this argument applies only on Windows agents)

#- bash: pip install pyyaml -U --upgrade-strategy eager
#  displayName: "Install pyyaml"
#- bash: pip install requests -U --upgrade-strategy eager
#  displayName: "Install requests"
#run python
#- task: PythonScript@0
#  inputs:
#    scriptSource: 'filePath'
#    scriptPath: 'RunTestsWithAppsurify.py'
#    arguments: '--url ''https://demo.appsurify.com'' --apikey ''MTU6a3Q1LUlTU3ZEcktFSTFhQUNoYy1DU3pidkdz'' --project ''Demo Andrew'' --testsuite ''Selenium'' --runtemplate ''prioritized tests with unassigned'' --testtemplate ''mvn demo'''
#    #pythonInterpreter: # Optional
#    #workingDirectory: # Optional
#    #failOnStderr: false # Optional
